### ISSUE TITLE
Bugs in integration branch

### ISSUE THREAD

**Issue by HeywardLiu** [yuko29/meteorological_center#14]
@Laxiflora 
Please remove `__filter_anomaly` and fix `__transfer_time_type` which can't handle "-" in `dbAPI.MongoDB` module.

**Comment by Laxiflora** [comment]
If none time value after crawling, db expects to get 'time':None instead of 'time': '-'

**Comment by Laxiflora** [comment]
Since 'time' was used to sort the latest data, DB expects 'time' column be datetime.datetime type. I will change '"time" to "1995-01-01 00:00:00", which may never being received unless DB is empty, proceed with caution.

**Comment by Laxiflora** [comment]
After discussion, we decided to filter anomaly (a.k.a NULL) values in crawling process and delete __filter_anomaly and __transfer_time_type function.
For DB insertion, we only verify whether type of necessary keys are valid or not.
